title: My Blog
email: abhinavkaushlya@gmail.com
description: My Personal Blog Site
baseurl: ""
url: ""
twitter_username: abhishalya
github_username:  abhishalya
linkedin_username: abhishalya

permalink: /:title
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# minima:
#   social_links:
#     twitter: abhishalya
#     github: abhishalya
#     facebook: kabhishalya
#     instagram: abhishalya
#     linkedin: abhishalya
#   skin: solarized-dark

show_excerpts: true

disqus:
  shortname: abhishalya
